name: "Prod Terraform Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main      

permissions:
  id-token: write
  contents: read
  

jobs:
    runs-on:  ubuntu-latest

    environment: prod

    steps: 
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      # ✅ Terraform setup (if not pre-installed on self-hosted)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/prod
        
      - name: Configure azurerm backend
        uses: ahmedig/terraform-azurerm-backend@v4
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource_group_name: backendrg
          container_name: backendcontainer
          storage_account_name: backendstorge

      # ✅ Init required before validate/plan
      - name: Terraform Init
        run: terraform init -input=false
        working-directory: environments/prod

      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: environments/prod        
      
      - name: Terraform Plan
        run: terraform plan -no-color -input=false -out=tfplan
        working-directory: environments/prod    

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        
  terraform-apply:    

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    needs: terraform-init-plan
    environment: prod   # ✅ approval gate for prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure azurerm backend
        uses: ahmedig/terraform-azurerm-backend@v4
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource_group_name: backendrg
          container_name: backendcontainer
          storage_account_name: backendstorge

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: environments/prod

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan || terraform apply -auto-approve
        working-directory: environments/prod
        
